### PR TITLE
New Style

### PR DESCRIPTION
**Pull request by alexvansande**
This PR changes nothing but text and styles. It adds no images. I understand some of this might get down to taste and some people will prefer the more simple version but I think the change in labels and some of the input fields increases accessibility. For example, in the beginning I was confused what each field meant or what was their importance.

Screen Shot 2020-06-11 at 1 14 15 PM
Screen Shot 2020-06-11 at 1 14 45 PM

Screen Shot 2020-06-11 at 1 34 51 PM

I don't mind not having this merged as some might not like it, so I will simply point to my fork.

### CODE REVIEW

**Comment by alexvansande** [comment]
[clabot:check]

**Comment by kirushik** [comment]
Hi, @alexvansande, thank you so much for improving my "programmer's design"!

I promise you I will finally get around to BS next week_-ish_ and merging this would be the first thing on my list. (Hope you understand that our other products are being released right now, and I won't have enough time to even read your PR thoroughly for a while.)

**Comment by alexvansande** [comment]
No worries @kirushik 
I built it mostly for me because I wanted to use banana split (thanks for building it!) and the design was itching me.

**Comment by kirushik** [comment]
I still think that this is awesome, but have two nits after reviewing it more thoroughly.
The small one is that I really liked my logical statements wrapped in brackets; it might be against certain Javascript code styles, I admit -- but when you jump from language to language I think some added explicitness won't hurt.
The bigger one is that printing is a bit broken (at least in Firefox on Linux, with default settings -- implying that browser's headers and footers are being printed). Those dotted margins overflow the page just a tiny bit, and in the end we're using 10 sheets of paper to print 5 QRs ( [mozilla.pdf](https://github.com/paritytech/banana_split/files/4801132/mozilla.pdf) ).

Those are rather trivial to fix -- but it seems that this PR doesn't have collaborator editing enabled for some reason, so maybe you would be so kind to fix them yourself? Opening a PR for your PR sounds like a terrible overkill...

**Comment by alexvansande** [comment]
I didn't intend to change any of the javascript logic, but maybe that's the autoformatting of my system – should've turned it off, you're right.  I was testing printing a lot but you're right that it should be fixed. I like printing my cards with 4 pages per page, so that the qr code is card sized, so that's why I added the dotted line, but we can remove it.

I have the collaborator editing turned on, you should be able to change anything–maybe I need to turn something else too? Of course I can change these on my side too.

Screen Shot 2020-06-22 at 11 45 34 AM

**Comment by alexvansande** [comment]
@kirushik 
I tweaked print styles a bit more, but honestly they are inconsistent accross browsers - specially when we start adding different sizes and oh my, landscape format.

**Comment by kirushik** [comment]
OK, this has been hanging open for too long (and again it's on me).
I'll merge it as is and then fix all my complaints in master.

Please subscribe to the releases if you want to be notified when 0.3.0 would be ready (it should be OK to host/use unreleased builds, but please mark those as such, so people would know that they are on their own and forwards/backwards compatibility hasn't been tested/guaranteed).

**Comment by alexvansande** [comment]
Thanks for the merge! I hope it works out!

**Pull request merged**
