### PR TITLE
Frontend

### PR DESCRIPTION
**Pull request by digitaldonkey**
Some UI improvements without Electron setup.

### CODE REVIEW

**Comment by ddorgan** [comment]
[clabot:check]

**Comment by ddorgan** [comment]
[clabot:check]

**Comment by digitaldonkey** [comment]
> it now allows typing in a secret while open from a web URL, and a download link no longer present. This is not OK, since users won't bother downloading the file unless they absolutely need to — and allowing using Banana Split by URL opens a significant attack vector for hackers.

That depends on which build you chose. 

```
"scripts": {
    "serve": "vue-cli-service serve",
    "dev": "vue-cli-service serve",
    "build": "vue-cli-service build",
    "electron": "electron-webpack dev",
    "electron-build": "electron-webpack && electron-builder",
    "electron-build-osx": "electron-webpack && electron-builder && dist/mac/banana_split.app/Contents/MacOS/banana_split",
    "deploy": "gh-pages -b gh-pages -d dist -a",
    "lint": "vue-cli-service lint",
    "test:unit": "vue-cli-service test:unit"
  },
```

`vue-cli-service build` should work as before. 

>Parity requires all GPL code contributors to sign-off their code using CLA. I understand that this is a controversial topic in the opensource community, and will understand if you consider this not acceptable and will revoke your PR; if you are OK with signing a CLA, please follow instructions from our friendly bot.

I love GPL :D 
Submitted bot stuff.

**Comment by digitaldonkey** [comment]
Check for:
https://github.com/digitaldonkey/banana_split/blob/bf48a3057715883e7e3e82466a54b00b61cc81a0/src/main.js#L17-L18

**Comment by digitaldonkey** [comment]
Check for **IS_ELECTRON_BUILD**

```javascript
Vue.prototype.IS_ELECTRON_BUILD = (process.env.npm_lifecycle_event && process.env.npm_lifecycle_event.includes('electron'))
                            || (process.config && process.config.variables.built_with_electron);
```

https://github.com/digitaldonkey/banana_split/blob/bf48a3057715883e7e3e82466a54b00b61cc81a0/src/main.js#L17-L18

**Comment by kirushik** [comment]
[clabot:check]

**Comment by kirushik** [comment]
@digitaldonkey 

> Check for **IS_ELECTRON_BUILD**


Hmmm...
Can it be that you forgot to include that file in this pull request? I don't see any changes for the `main.js` in this pull request, unfortunately (please see the "Files changed' tab). Also, as of commit 0fc3389c75dfaacd53bae3eb3bf05c90f2a6b2c2, string `IS_ELECTRON_BUILD` is not mentioned anywhere in the code.

Can you please double-check that this PR contains everything you intended to submit?

**Comment by digitaldonkey** [comment]
Seems I added that to the wrong pull request. It relates to my electron
branch.

Kirill Pimenov <notifications@github.com> schrieb am Di., 14. Mai 2019,
17:59:

**Comment by kirushik** [comment]
Closing this one due to merge conflicts.
If you still want to wrap this in electron (or, even better, [tauri](https://github.com/tauri-apps/tauri)) -- please open an issue and let's discuss what would be needed on the BananaSplit side to make your maintenance of such wrapping as easy as possible.
(I still keep my position that having such a wrapper is out of scope for the BS project itself)

**Pull request closed without merging**
