### PR TITLE
always show git hash in bs version

### PR DESCRIPTION
**Pull request by prybalko**
For a tagged commit it's going to be`v0.3.0-0-g2c91c85`

### CODE REVIEW

**Comment by kirushik** [comment]
@prybalko well, we can't retroactively apply that to the existing 0.3.0, can we?
Please tag 0.3.1 with this patch in and deploy to bs.parity.io

**Review by kirushik — APPROVED** [review]

**Comment by prybalko** [comment]
I think I can edit/remove exising tags

**Comment by prybalko** [comment]
UPD: removed `v0.3.0` tag.

**Comment by kirushik** [comment]
@prybalko currently https://bs.parity.io/ says `v0.2.0-91-g2c91c85` — which doesn't feel accurate to me.

Can we please in the future make releases of BananaSplit a big, manual thing?
It's not your regular webservice which can be patched in a jiffy, each release is expected to stay with its users **for years** without much in a way of updating.
We can't afford people getting random occasional versions without even clear versioning — and then sticking to them.

**Review by vas3k — APPROVED** [review]

**Pull request merged**
