### PR TITLE
Electron Version

### PR DESCRIPTION
**Pull request by digitaldonkey**
Includes heavy UI changes, but compiles also as single page app. 

There is a [less heavy version](https://github.com/digitaldonkey/banana_split/tree/frontend ) available too. It only includes some of the UX changes. 

A very few adoptions are made only for the Electron version. Check for `IS_ELECTRON_BUILD`.
Currently I only tested the OSX version, but OS releases may be added if you like that approach.

Check out Electron Version at [banana_split.zip](https://donkeymedia.eu/banana_split.zip) (it will tell you I'm not trustworthy, because it's not signed by a Certified Apple developer)

image

image

image

### CODE REVIEW

**Comment by digitaldonkey** [comment]
Another sin commited: I switched from yarn to npm, which might break the build system.

**Comment by kirushik** [comment]
@digitaldonkey Hello! Sorry for the delay, I somehow ended up not subscribed to PRs in my own repos, so this came totally overlooked. I apologise for that.

As for your PR, I don't mind someone maintaining Electron version of Banana Split (and will link to that project from the top of my README with pleasure), but I don't think that Electron should be the default mode for Banana Split, so it's not something I'm going to maintain myself.

This is not an easy choice, but my rationale is the following:
1) It's important for Banana Split to be portable, in a sense "you've downloaded it once, archived somewhere — and then it's usable on any computer you'll happen to have in 10 years, regardless of platform or ABI changes". Unfortunately, I don't trust Electron apps to guarantee that (and standalone HTML is probably our best bet).
2) It's important for Banana Split to minimize surface for supply chain attacks. I'm currently investigating putting my releases to IPFS, so there're more integrity/immutability guarantees provided — and having multiple different "electronized" binaries for every release makes this attack surface larger.
3) It's important to make Banana Split compatible with mobile devices, and putting (and maintaining) Electron app in those markets is significantely more involved than keeping "one HTML fits all" file online. (Also supply chain attacks again.)


Once again, I am really grateful for you doing this, and will link and support you as much as I can — but maintaining Electron app is not something I'm willing to take on myself.


Let's keep this PR open till we figure out how and where should I link, how to make upstream BananaSplit more maintainable for Electron fork and so on.
PS. have you lloked at [DeskGap](https://deskgap.com/)? It seems to be a lighter alternative to Electron, leveraging platform-native WebView instead of embedded renderer. Since we need to write pretty platform-agnostic HTML+JS in BananaSplit anyway, I don't foresee any major problems with platform-native renderers (and the resulting app will be much more lightweight)

**Comment by digitaldonkey** [comment]
The pure HTML version still works with this PR, but I understand your worries too. 
There are also a lot of UX improvements in t PR. I created a second one without Electron.

**Comment by kirushik** [comment]
@digitaldonkey Thank you!
Really, if you want to maintain Electron-wrapped Banana Split, I will be glad to link there!

Also thank you for UI improvements; this PR is superseded by #17

**Comment by ddorgan** [comment]
[clabot:check]

**Pull request closed without merging**
