### PR TITLE
style: UI

### PR DESCRIPTION
**Pull request by goldsteinsveta**
This PR is all about making on-screen part of the bs more user friendly (read instructions, scan for sequencing, detect state changes) and its UI more compact and conventional.

Frame 1
This is a generated secret screen, full design ref lives [here](https://www.figma.com/file/1y9plf3EH22LBMOrydZD9o/Banana-Split?node-id=0%3A1)

It is not about wording, copy and print part of the bs. Looking forward to feedback for this one to proceed with these too :)

### CODE REVIEW

**Review by kirushik — APPROVED** [review]
I really like the new styles — frames, shades, how compact it all looks...
The only thing I would like to suggest is moving the "Split" and "Combine" buttons to the bottom — otherwise the first experience is a bit confusing: you went offline, read the intro, and now what?

I've also noticed that on certain smaller mobile screens the Split/Combine bar overflows and jumps under the "What is this" description text — yet another reason to move it down.

I'm not certain if all that needs to be fixed in the pullrequest or in a separate one — so please merge at will.

**Comment by goldsteinsveta** [comment]
I've just quick fixed it for >530px screens and Uh! Interesting, I personally found it confusing not to have the navigation at the top, as that appears to be the first place my eyes looking at. But I see what you saying about guiding the user to the nav after reading instructions. Let me figure something out in the next PR.

I don't not have rights to merge myself! Don't mind getting rights or working on this branch

**Review by kirushik — APPROVED** [review]

**Comment by kirushik** [comment]
@goldsteinsveta please DM me to set up commit signing; it's generally a good practice, and is a must for a project like BananaSplit (thus it's enforced on all pull requests and I cannot merge unfortunately).

**Review by kirushik — APPROVED** [review]
:heart_decoration:

**Pull request merged**
